version: '3.9'
services:
  web_service:
    depends_on:
      - agg-db
    build: 
      context: ./web_service/
      dockerfile: Dockerfile
    image: aggregator:v1
    env_file:
      - web_service/.env
    restart: always
    volumes:
      - static_data:/app/vol/web/static/
    command: >
         sh -c 'sh /app/migrate.sh && /app/entrypoint.sh'
    
  agg-db:
    image: postgres:14-alpine3.16
    restart: always
    command: -p 5433
    env_file:
      - web_service/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./populatedb.sql:/docker-entrypoint-initdb.d/init.sql
      - ./eda_cleaned.csv:/docker-entrypoint-initdb.d/eda_cleaned.csv

  proxy:
    build:
      context: ./web_proxy
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - web_service
    ports:
      - 80:8000
    volumes:
      - static_data:/vol/static/

    
volumes:
  static_data:
  postgres_data:
  populatedb.sql:
  eda_cleaned.csv: